services:
  - type: web
    name: budget-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1